version: '2'
services:
  tutorialaprendiendo-app:
    image: tutorialaprendiendo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://tutorialaprendiendo-mysql:3306/tutorialaprendiendo?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8040:8040
  tutorialaprendiendo-mysql:
    extends:
      file: mysql.yml
      service: tutorialaprendiendo-mysql
