- name: Deploy docker-compose
  # You may pin to the exact commit or the version.
  # uses: hasnat/deploy-docker-compose@cb95ae68efbc7c6dbd9c86cb851dc2ad9ff19625
  uses: hasnat/deploy-docker-compose@v0.1-alpha
  with:
    copy_stack_file: true
    deploy_path: /root/my-deployment
    stack_file_name: docker/mysql.yml
